# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[4,)" #mandatory
# A URL to refer people to when problems occur with this mod
issueTrackerURL = "https://github.com/Sarenor/Ars-Instrumentum/issues" #optional

license = "GNU Lesser General Public License v3.0"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "ars_instrumentum" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version = "${file.jarVersion}" #mandatory
# A display name for the mod
displayName = "Ars Instrumentum" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="ars_instrumentum.png" #optional
# A text field displayed in the mod UI
credits="Thanks for this example mod goes to the Ars Nouveau Discord who made me try my hand at modding, specifically to Bailey for providing an easy starter" #optional
# A text field displayed in the mod UI
authors="No one important, and Alexthw" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Ars Instrumentum is a small set of magical utilities and tools that I wanted to have in addition to Ars Nouveau
'''
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"
[[mixins]]
config = "ars_instrumentum.mixins.json"

[[dependencies.ars_instrumentum]]
modId = "minecraft"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
type="required"

[[dependencies.ars_instrumentum]]
modId = "ars_nouveau"
versionRange = "[1.21.1-5.4,)"
ordering = "AFTER"
side = "BOTH"
type="required"